
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RARROW = 5;
  public static final int STRING_LITERAL = 2;
  public static final int LTE = 34;
  public static final int BOX_OUT = 26;
  public static final int ASTERISK = 17;
  public static final int EMPTY = 23;
  public static final int EMJ_SAD = 28;
  public static final int ANYCHAR = 4;
  public static final int SPIN = 30;
  public static final int LRARROW = 7;
  public static final int SPEAKER = 38;
  public static final int MINUS = 19;
  public static final int SQUOTE = 11;
  public static final int SEMICOLON = 13;
  public static final int LT = 33;
  public static final int COMMA = 37;
  public static final int QMARK = 16;
  public static final int DIV = 20;
  public static final int RHAND = 9;
  public static final int PLUS = 18;
  public static final int EOF = 0;
  public static final int DQUOTE = 12;
  public static final int error = 1;
  public static final int EMJ_SMILE = 27;
  public static final int PERCENT = 22;
  public static final int HAT = 21;
  public static final int NUMBER = 15;
  public static final int GTE = 32;
  public static final int FLASH = 29;
  public static final int VARIABLE = 14;
  public static final int EE = 35;
  public static final int NE = 36;
  public static final int UCHAR = 3;
  public static final int OPERATOR = 39;
  public static final int HALTHAND = 10;
  public static final int BOX_IN = 25;
  public static final int RDARROWSTOP = 8;
  public static final int CYCLE = 24;
  public static final int GT = 31;
  public static final int RDARROW = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING_LITERAL",
  "UCHAR",
  "ANYCHAR",
  "RARROW",
  "RDARROW",
  "LRARROW",
  "RDARROWSTOP",
  "RHAND",
  "HALTHAND",
  "SQUOTE",
  "DQUOTE",
  "SEMICOLON",
  "VARIABLE",
  "NUMBER",
  "QMARK",
  "ASTERISK",
  "PLUS",
  "MINUS",
  "DIV",
  "HAT",
  "PERCENT",
  "EMPTY",
  "CYCLE",
  "BOX_IN",
  "BOX_OUT",
  "EMJ_SMILE",
  "EMJ_SAD",
  "FLASH",
  "SPIN",
  "GT",
  "GTE",
  "LT",
  "LTE",
  "EE",
  "NE",
  "COMMA",
  "SPEAKER",
  "OPERATOR"
  };
}

